//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.StoredProcedures {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SP() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.StoredProcedures.SP", typeof(SP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CalculateSalaryAndCompensation.
        /// </summary>
        internal static string CalculateSalaryAndCompensation {
            get {
                return ResourceManager.GetString("CalculateSalaryAndCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get_EmployeeById.
        /// </summary>
        internal static string Get_EmployeeById {
            get {
                return ResourceManager.GetString("Get_EmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get_MovementById.
        /// </summary>
        internal static string Get_MovementById {
            get {
                return ResourceManager.GetString("Get_MovementById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAll_Months.
        /// </summary>
        internal static string GetAll_Months {
            get {
                return ResourceManager.GetString("GetAll_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAll_Rol.
        /// </summary>
        internal static string GetAll_Rol {
            get {
                return ResourceManager.GetString("GetAll_Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactivate_Employee.
        /// </summary>
        internal static string Inactivate_Employee {
            get {
                return ResourceManager.GetString("Inactivate_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactivate_Movement.
        /// </summary>
        internal static string Inactivate_Movement {
            get {
                return ResourceManager.GetString("Inactivate_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save_Employee.
        /// </summary>
        internal static string Save_Employee {
            get {
                return ResourceManager.GetString("Save_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save_Movement.
        /// </summary>
        internal static string Save_Movement {
            get {
                return ResourceManager.GetString("Save_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update_Employee.
        /// </summary>
        internal static string Update_Employee {
            get {
                return ResourceManager.GetString("Update_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update_Movement.
        /// </summary>
        internal static string Update_Movement {
            get {
                return ResourceManager.GetString("Update_Movement", resourceCulture);
            }
        }
    }
}
